backend = "glx";

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

corner-radius = 0;
frame-opacity = 0.7;

# Tell Picom to follow IceWM active window focus
use-ewmh-active-win = true;

rules: (
  # Menu opacity (replaces wintypes)
  {
    match = "window_type = 'dropdown_menu' || window_type = 'popup_menu'";
    opacity = 0.9;
  },
# Custom btop rule
  {
    match = "name *= 'btop' || class_g = 'btop-float' || class_i = 'btop-float'";
    opacity = 0.80;
  }
)
